add JSON alternative support
erfanium/atlas_sdk pull request #29
Opened 2023-06-20 18:05 UTC by UrielCh

2023-06-20 18:19 UTC, erfanium requested changes

2023-06-20 18:19 UTC, erfanium commented on client.ts
> +  encoding?: 'JSON' | 'EJSON'
```suggestion
  contentType?: 'ejson' | 'json';
```

it's not really about encoding.

2023-06-20 18:20 UTC, erfanium commented
also you missed the `return EJSON.parse(body);` at [line](https://github.com/erfanium/atlas_sdk/blob/b9ccb49a6593f2273e4317f4b51e165d516e6566/client.ts#L230)

2023-06-20 18:21 UTC, UrielCh commented on client.ts
> +  encoding?: 'JSON' | 'EJSON'
I'm still on it...

2023-06-20 18:22 UTC, erfanium commented
The rest is looking good to me. Thanks!

2023-06-20 18:56 UTC, erfanium commented
@UrielCh please check this out.

> also you missed the return EJSON.parse(body); at [line](https://github.com/erfanium/atlas_sdk/blob/b9ccb49a6593f2273e4317f4b51e165d516e6566/client.ts#L230)

2023-06-20 19:11 UTC, UrielCh commented
I had completed my change, That do not fix my issue, but I think the code is fine.

2023-06-20 19:13 UTC, UrielCh commented on client.ts
> +      body,
this change was mostly for debugging and trying to write this statement in a single line, but fmt thinks that statement is still too long ... 80 char is so small...

2023-06-24 08:40 UTC, erfanium commented
@UrielCh 
Hey!
Thanks for you PR, but I have no idea in which real-world case, using `json` over `ejson` would be useful.

I'm not going to close this PR, I'll hit the merge button as soon as we get a few more thumbs up on it.
so i think you could just continue using your fork.

2023-06-24 20:54 UTC, UrielCh commented
I'm still improving my MongoDB request-building skills.

I may or may not find an actual usage for the JSON encoder.

2024-03-24 14:19 UTC, closed without merging